import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";
import { AuthProvider } from "@/components/auth-provider";
import { LogoutButton } from "@/components/LogoutButton";
import { getServerAuth } from "@/lib/auth";

const generalSans = localFont({
  src: [
    {
      path: "../../public/fonts/GeneralSans-Extralight.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/GeneralSans-ExtralightItalic.otf",
      weight: "200",
      style: "italic",
    },
    {
      path: "../../public/fonts/GeneralSans-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/GeneralSans-LightItalic.otf",
      weight: "300",
      style: "italic",
    },
    {
      path: "../../public/fonts/GeneralSans-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/GeneralSans-Italic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../public/fonts/GeneralSans-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/GeneralSans-MediumItalic.otf",
      weight: "500",
      style: "italic",
    },
    {
      path: "../../public/fonts/GeneralSans-Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/GeneralSans-SemiboldItalic.otf",
      weight: "600",
      style: "italic",
    },
    {
      path: "../../public/fonts/GeneralSans-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/GeneralSans-BoldItalic.otf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-general-sans",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authState = await getServerAuth();
  const email = authState.user?.email;

  return (
    <html lang="en">
      <body
        className={`${generalSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider initialState={authState}>
          {/* <div className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between border-b border-black/5 bg-white/80 px-6 py-3 backdrop-blur">
            <Link href="/" className="text-sm font-medium text-blue-700">
              Mediva AI
            </Link>
            <div className="flex items-center gap-4 text-xs text-muted-foreground">
              {email ? (
                <>
                  <span>{email}</span>
                  <LogoutButton />
                </>
              ) : (
                <Link href="/login">Masuk</Link>
              )}
            </div>
          </div> */}
          <div className="pt-16">{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
